name: gradiend
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.1.0
  - accelerate=1.0.0
  - aiohappyeyeballs=2.4.3
  - aiohttp=3.10.9
  - aiosignal=1.3.1
  - alembic=1.13.3
  - alsa-lib=1.2.12
  - annotated-types=0.6.0
  - anyio=4.6.0
  - aom=3.6.1
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - async-timeout=4.0.3
  - attrs=24.2.0
  - aws-c-auth=0.7.31
  - aws-c-cal=0.7.4
  - aws-c-common=0.9.28
  - aws-c-compression=0.2.19
  - aws-c-event-stream=0.4.3
  - aws-c-http=0.8.10
  - aws-c-io=0.14.18
  - aws-c-mqtt=0.10.7
  - aws-c-s3=0.6.6
  - aws-c-sdkutils=0.1.19
  - aws-checksums=0.1.20
  - aws-crt-cpp=0.28.3
  - aws-sdk-cpp=1.11.407
  - azure-core-cpp=1.13.0
  - azure-identity-cpp=1.9.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=6.1.0
  - bokeh=3.4.3
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.1
  - ca-certificates=2025.9.9
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.0
  - catalogue=2.0.10
  - certifi=2025.10.5
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - click=8.1.7
  - cloudpathlib=0.16.0
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - colorlog=6.8.2
  - comm=0.2.2
  - confection=0.1.4
  - contourpy=1.3.0
  - cuda-cudart=12.4.99
  - cuda-cudart_linux-64=12.4.99
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.0
  - cuda-nvrtc=12.4.99
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.4.99
  - cuda-runtime=12.4.0
  - cuda-version=12.4
  - cycler=0.12.1
  - cymem=2.0.6
  - cyrus-sasl=2.1.27
  - cython-blis=0.7.9
  - cytoolz=1.0.1
  - dask=2024.5.0
  - dask-core=2024.5.0
  - dask-expr=1.1.0
  - datasets=3.0.2
  - dbus=1.13.6
  - debugpy=1.8.6
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.8
  - distributed=2024.5.0
  - double-conversion=3.3.0
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.3
  - ffmpeg=4.4.2
  - filelock=3.16.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.54.1
  - fqdn=1.5.1
  - freetype=2.12.1
  - frozenlist=1.4.1
  - fsspec=2024.6.1
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gflags=2.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.1.5
  - gnutls=3.7.9
  - graphite2=1.3.13
  - greenlet=3.1.1
  - grpcio=1.65.5
  - h11=0.14.0
  - h2=4.1.0
  - harfbuzz=9.0.0
  - heapdict=1.0.1
  - hpack=4.0.0
  - httpcore=1.0.6
  - httpx=0.27.2
  - huggingface_hub=0.25.2
  - humanize=4.12.1
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib-resources=6.4.5
  - importlib_metadata=8.5.0
  - importlib_resources=6.4.5
  - inflect=7.4.0
  - intel-openmp=2022.0.1
  - ipykernel=6.29.5
  - ipython=8.18.1
  - ipywidgets=8.1.5
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - json5=0.9.25
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.2
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.2.5
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lame=3.100
  - langcodes=3.3.0
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lemminflect=0.2.2
  - lerc=4.0.0
  - libabseil=20240722.0
  - libarrow=17.0.0
  - libarrow-acero=17.0.0
  - libarrow-dataset=17.0.0
  - libarrow-substrait=17.0.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp19.1=19.1.1
  - libclang13=19.1.1
  - libcrc32c=1.1.2
  - libcublas=12.4.2.65
  - libcufft=11.2.0.44
  - libcufile=1.9.0.20
  - libcups=2.3.3
  - libcurand=10.3.5.119
  - libcurl=8.10.1
  - libcusolver=11.6.0.99
  - libcusparse=12.3.0.142
  - libdeflate=1.22
  - libdrm=2.4.123
  - libedit=3.1.20191231
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.3
  - libffi=3.4.2
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libgl=1.7.0
  - libglib=2.82.1
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.1.0
  - libgoogle-cloud=2.29.0
  - libgoogle-cloud-storage=2.29.0
  - libgrpc=1.65.5
  - libiconv=1.17
  - libidn2=2.3.7
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm19=19.1.1
  - libnghttp2=1.58.0
  - libnpp=12.2.5.2
  - libnsl=2.0.1
  - libntlm=1.4
  - libnvfatbin=12.4.99
  - libnvjitlink=12.4.99
  - libnvjpeg=12.3.1.89
  - libopengl=1.7.0
  - libparquet=17.0.0
  - libpciaccess=0.18
  - libpng=1.6.44
  - libpq=17.0
  - libprotobuf=5.27.5
  - libre2-11=2023.11.01
  - libsodium=1.0.20
  - libsqlite=3.46.1
  - libssh2=1.11.0
  - libstdcxx=14.1.0
  - libstdcxx-ng=14.1.0
  - libtasn1=4.19.0
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libva=2.22.0
  - libvpx=1.13.1
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.7.0
  - libxml2=2.12.7
  - libxslt=1.1.39
  - libzlib=1.3.1
  - lightning-utilities=0.11.9
  - llvm-openmp=15.0.7
  - locket=1.0.0
  - lz4=4.3.2
  - lz4-c=1.9.4
  - mako=1.3.5
  - markdown=3.6
  - markdown-it-py=2.2.0
  - markupsafe=3.0.1
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - mdurl=0.1.0
  - mistune=3.0.2
  - mkl=2022.1.0
  - more-itertools=10.5.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msgpack-python=1.0.7
  - multidict=6.1.0
  - multiprocess=0.70.16
  - munkres=1.1.4
  - murmurhash=1.0.12
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - nbclient=0.10.0
  - nbconvert-core=7.16.4
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.9.1
  - networkx=3.2.1
  - nltk=3.9.1
  - notebook=7.2.2
  - notebook-shim=0.2.4
  - numpy=1.26.4
  - ocl-icd=2.3.2
  - openh264=2.3.1
  - openjpeg=2.5.2
  - openldap=2.6.8
  - openssl=3.4.1
  - optuna=4.0.0
  - orc=2.0.2
  - overrides=7.7.0
  - p11-kit=0.24.1
  - packaging=24.1
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - parso=0.8.4
  - partd=1.4.2
  - patsy=0.5.6
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - pixman=0.43.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - plotly=5.24.1
  - preshed=3.0.9
  - prometheus_client=0.21.0
  - prompt-toolkit=3.0.48
  - prompt_toolkit=3.0.48
  - protobuf=5.27.5
  - psutil=6.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=17.0.0
  - pyarrow-core=17.0.0
  - pycparser=2.22
  - pydantic=2.10.3
  - pydantic-core=2.27.1
  - pygments=2.18.0
  - pynvml=11.5.3
  - pyparsing=3.1.4
  - pyside6=6.7.3
  - pysocks=1.7.1
  - python=3.9.19
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.20.0
  - python-json-logger=2.0.7
  - python-lmdb=1.6.2
  - python-tzdata=2024.2
  - python-xxhash=3.5.0
  - python_abi=3.9
  - pytorch=2.4.1
  - pytorch-cuda=12.4
  - pytorch-lightning=2.5.3
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - qt6-main=6.7.3
  - re2=2023.11.01
  - readline=8.2
  - referencing=0.35.1
  - regex=2024.9.11
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.9.4
  - rpds-py=0.20.0
  - s2n=1.5.4
  - safetensors=0.4.5
  - scikit-learn=1.5.2
  - scipy=1.13.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=75.1.0
  - shellingham=1.5.0
  - six=1.16.0
  - smart_open=5.2.1
  - snappy=1.2.1
  - sniffio=1.3.1
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - spacy=3.7.2
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.4
  - sqlalchemy=2.0.35
  - srsly=2.5.1
  - stack_data=0.6.2
  - statsmodels=0.14.4
  - svt-av1=1.4.1
  - swifter=1.4.0
  - sympy=1.13.3
  - tabulate=0.9.0
  - tblib=3.1.0
  - tenacity=9.0.0
  - tensorboard=2.18.0
  - tensorboard-data-server=0.7.0
  - terminado=0.18.1
  - thinc=8.2.2
  - threadpoolctl=3.5.0
  - tinycss2=1.3.0
  - tk=8.6.13
  - tokenizers=0.20.0
  - tomli=2.0.2
  - toolz=1.0.0
  - torchaudio=2.4.1
  - torchmetrics=1.5.2
  - torchtriton=3.0.0
  - torchvision=0.19.1
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - transformers=4.45.2
  - typeguard=4.3.0
  - typer=0.9.0
  - types-python-dateutil=2.9.0.20241003
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2024b
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - urllib3=2.2.3
  - wasabi=0.9.1
  - wayland=1.23.1
  - wayland-protocols=1.37
  - wcwidth=0.2.13
  - weasel=0.3.4
  - webcolors=24.8.0
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - werkzeug=3.0.4
  - wheel=0.44.0
  - widgetsnbextension=4.0.13
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.43
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.10
  - xorg-libxau=1.0.11
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.2
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.11
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.5
  - xorg-xorgproto=2024.1
  - xxhash=0.8.2
  - xyzservices=2022.9.0
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.13.1
  - zeromq=4.3.5
  - zict=3.0.0
  - zipp=3.20.2
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - en-core-web-sm==3.7.1
      - pyaml==25.7.0
      - pympler==1.1
      - scikit-optimize==0.10.2
      - sentencepiece==0.2.0
      - sns==0.1