"""
English pronoun workflow: 3SG (he/she/it) vs 3PL (they) — singular vs plural.

Loads from data generated by data_creation_pronouns, trains a GRADIEND model.

To learn number (singular vs plural) from all pronouns, use class_merge_map:
    class_merge_map={"singular": ["1SG", "3SG"], "plural": ["1PL", "3PL"]}
With exactly two merged classes, target_classes can be omitted.

Requires: pip install gradiend[data]

You need to run data_creation_pronouns before this to create the data it needs (or create your own data in the same format). The data should be in runs/examples/data/english_pronouns/ (or change DATA_DIR to point to it). The training data should be in training.csv and the neutral eval data in neutral.csv. The training data should have a "text" column and a "label" column with values "3SG" or "3PL". The neutral data should have a "text" column and no labels, and should not contain any of the target pronouns.
"""

from pathlib import Path

from gradiend import (
    TextPredictionTrainer,
    TextPredictionConfig,
    TrainingArguments,
)

# Output folder for generated data; trainer uses this
DATA_DIR = "data/english_pronouns"


def main():
    base = Path(DATA_DIR)
    training_path = base / "training.csv"
    neutral_path = base / "neutral.csv"

    config = TextPredictionConfig(
        run_id="pronoun_3sg_3pl",
        data=training_path,
        target_classes=["3SG", "3PL"],
        eval_neutral_data=neutral_path,

    )

    args = TrainingArguments(
        experiment_dir="runs/english_pronouns",
        train_batch_size=4,
        eval_steps=25,
        num_train_epochs=5,
        max_steps=500,
        source="alternative",
        target="diff",
        eval_batch_size=4,
        learning_rate=1e-3,

    )

    print("\n=== Training ===")
    trainer = TextPredictionTrainer(
        model="bert-base-uncased",
        config=config,
        args=args,
    )
    trainer.train()
    trainer.plot_training_convergence()

    stats = trainer.get_training_stats()
    ts = stats.get("training_stats", {}) if stats else {}
    print(f"  correlation={ts.get('correlation')}")

    print("\n=== Encoder evaluation ===")
    trainer.evaluate_encoder(plot=True)
    enc_metrics = trainer.get_encoder_metrics(use_cache=True)
    print(f"  {enc_metrics}")

    print("\n=== Decoder evaluation ===")
    dec = trainer.evaluate_decoder(plot=True)
    stats = dec["3SG"]
    print(stats)
    print("\n=== Done ===")


if __name__ == "__main__":
    main()
