"""
English pronoun workflow: 3SG (he/she/it) vs 3PL (they) — singular vs plural.

Loads from data generated by data_creation_pronouns, trains a GRADIEND model.

To learn number (singular vs plural) from all pronouns, use class_merge_map:
    class_merge_map={"singular": ["1SG", "3SG"], "plural": ["1PL", "3PL"]}
With exactly two merged classes, target_classes can be omitted.

Requires: pip install gradiend[data] transformers torch datasets
"""

from pathlib import Path

from gradiend import (
    TextPredictionTrainer,
    TextPredictionConfig,
    TrainingArguments,
)

# Output folder for generated data; trainer uses this
DATA_DIR = "data/english_pronouns"


def main():
    base = Path(DATA_DIR)
    training_path = base / "training.csv"
    neutral_path = base / "neutral.csv"

    config = TextPredictionConfig(
        run_id="pronoun_3sg_3pl",
        data=training_path,
        target_classes=["3SG", "3PL"],
        eval_neutral_data=neutral_path,
        # class_merge_map={"singular": ["1SG", "3SG"], "plural": ["1PL", "3PL"]},
    )

    args = TrainingArguments(
        experiment_dir="runs/english_pronouns",
        train_batch_size=8,
        eval_steps=100,
        num_train_epochs=2,
        max_steps=500,
        source="factual",
        target="diff",
        eval_batch_size=4,
        learning_rate=1e-4,
    )

    print("\n=== Training ===")
    trainer = TextPredictionTrainer(
        model="bert-base-uncased",
        config=config,
        args=args,
    )
    trainer.train()
    trainer.plot_training_convergence()

    stats = trainer.get_training_stats()
    ts = stats.get("training_stats", {}) if stats else {}
    print(f"  correlation={ts.get('correlation')}")

    print("\n=== Encoder evaluation ===")
    trainer.evaluate_encoder(plot=True)
    enc_metrics = trainer.get_encoder_metrics(split="train")
    if enc_metrics:
        print(f"  {enc_metrics}")

    print("\n=== Decoder evaluation ===")
    dec = trainer.evaluate_decoder()
    summary = dec.get("summary", {})
    if summary:
        for k, v in summary.items():
            if isinstance(v, dict) and "value" in v:
                print(f"  {k}: {v.get('value')}")
    print("\n=== Done ===")


if __name__ == "__main__":
    main()
